version: '3.7'

services:
  client:
    image: node:alpine
    container_name: vet_client
    expose: [8080]
  
  server:
    image: node:alpine
    container_name: vet_server
    expose: [2370]

  mongo:
    image: mongo:bionic
    container_name: vet_mongo
    restart: always
    expose: [27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: vetmongo
      MONGO_INITDB_ROOT_PASSWORD: vetmongo
      MONGO_INITDB_DATABASE: vetdb

  mongo-express:
    image: mongo-express
    container_name: vet_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vetmongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: vetmongo

networks: 
    default:
        name: vetmongo_default
        driver: bridge
