version: '3.7'

services:
  server:
    image: node:alpine
    container_name: vet_server
    expose: [2370]
    ports: 
      - 2370:2370
    working_dir: /home/node/app
    volumes: 
      - ./server:/home/node/app
    command: "npm run server"

  mongo:
    image: mongo:bionic
    container_name: vet_mongo
    restart: always
    expose: [27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: vetmongo
      MONGO_INITDB_ROOT_PASSWORD: vetmongo
      MONGO_INITDB_DATABASE: vetdb

  mongo-express:
    image: mongo-express
    container_name: vet_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: vetmongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: vetmongo

networks: 
    default:
        name: vetmongo_default
        driver: bridge
